import "./css/globals.css";
import Nav from "./_ui/Nav";
import Footer from "./_ui/Footer";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Lyricky",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Toaster
          position="top-center"
          toastOptions={{
            className: "",
            style: {
              border: "1px solid purple",
            },
          }}
        />

        <div className="container">
          <div></div>
          <main>
            <Nav />
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
